### ISSUE TITLE
IPv6 redirect Support?

### ISSUE THREAD

**Issue by azure9** [hmgle/graftcp#10]
Do you have plan support ipv6 proxy?

**Comment by hmgle** [comment]
It does support IPv6. This line:
https://github.com/hmgle/graftcp/blob/db56ea4a31359d8b9adcd57b24f1feadb5ed6a83/graftcp-local/local.go#L178

will call [net.Dial](https://github.com/golang/go/blob/bfaf11c158b5ccd7db3c43727357b8b1071d7fde/src/net/dial.go#L309) that support IPv6.

But if your local network or ISP does not support IPv6, the remote IPv6 proxy is unable to be reached.

**Comment by azure9** [comment]
Seems the graftcp part not hijack ipv6 flow, e.g. you can setup a shadowsocks server using shadowsocks-libev, and the flow won't be redirect by graftcp while at same time IPv4 works fine.

**Comment by hmgle** [comment]
Oh, I see. This line https://github.com/hmgle/graftcp/blob/db56ea4a31359d8b9adcd57b24f1feadb5ed6a83/graftcp.h#L40
`s_addr` is IPv4 only.
Thank you for your feedback.

**Comment by hmgle** [comment]
Oh, I see. This line https://github.com/hmgle/graftcp/blob/db56ea4a31359d8b9adcd57b24f1feadb5ed6a83/graftcp.h#L40
`s_addr` is IPv4 only.
Thank you for your feedback.

**Comment by hmgle** [comment]
IPv4/IPv6 dual-stack  feature is under development on the [ipv6 branch](https://github.com/hmgle/graftcp/tree/ipv6).
