### ISSUE TITLE
怎么个理论上能实现 mac os 版的 graftcp，DTrace 貌似只是个探针。

### ISSUE THREAD

**Issue by fanpei91** [hmgle/graftcp#12]
正如你所说，mac os 的 ptrace 是个半残品，也提到了理论上参考 DTrace 那一套也能实现，但是我简单了解了下 DTrace, 它并不能修改操纵被跟踪的程序，纯粹就是个探针。

还请指教下，怎么个理论上能实现？我想躺这趟浑水。一直好奇 [proxifier](https://www.proxifier.com/) 是怎么在 mac os 里做到跟 graftcp 一样的效果。

感谢你写的如此好的程序。

**Comment by hmgle** [comment]
@fanpei91 你好。
今天我重新看了下 DTrace 相关资料，发现是我之前对 DTrace 理解有误，如你所说，它对标的是 strace，作为工具并没有提供修改被跟踪程序参数机制。

对于 ptroxifier 这方面的能力，从[这个链接](https://www.securify.nl/en/advisory/SFY20170401/multiple-local-privilege-escalation-vulnerabilities-in-proxifier-for-mac.html)来看，应该是依赖了 Kernel Extension 这一套。对于 macOS 的 kext 这方面我没有太多的了解，期待你在这方面有所突破。

**Comment by fanpei91** [comment]
好的，我试试看。

**Comment by yangchuansheng** [comment]
@fanpei91 大哥，有进展了吗
