### ISSUE TITLE
EnvironmentFile=-/etc/sysconfig/graftcp-local

### ISSUE THREAD

**Issue by 1v9** [hmgle/graftcp#13]
Ubuntu 18.10 make install 过后, 没有生成环境参数文件.
查找后发现我电脑上没有 /etc/sysconfig 这个目录, 不过没有影响, 我目前 socks 代理等同默认设置.
最后感谢作者, 用此工具新开终端配合 ss-local 的 acl 模式, repo 命令完美工作.

**Comment by hmgle** [comment]
@1v9 你好。
graftcp-local 启动时会尝试读取与 graftcp-local 同一目录的`graftcp-local.conf`配置文件。如果要配置不同的参数的话，可以把 `example-graftcp-local.conf` 复制为 `graftcp-local.conf`, 然后根据需要修改里面的参数。对于默认使用 systemd 的 ubuntu 18.10, 更新完配置文件后，执行 `sudo systemctl restart graftcp-local` 后就生效了。

**Comment by 1v9** [comment]
@hmgle 多谢, 问题顺利解决.
