### ISSUE TITLE
Proxy Password

### ISSUE THREAD

**Issue by kevin-stuart** [hmgle/graftcp#19]
Is there a way to supply a username/password for a proxy? I did not see it documented. I tried username:password@address as proxy string. I also tried setting the SOCKS_USERNAME and SOCKS_PASSWORD environment variables.

A search for "password" yields graftcp-local/http_proxy.go, but this should not work for a socks proxy? I am also not sure how it should be set for the http proxy.

**Comment by hmgle** [comment]
The SOCKS5's username and password parameters are not supported now.
The http proxy's username and password can be passed like this:
 `http_proxy = http://USERNAME:PASSWORD@PROXYIP:PROXYPORT`

**Comment by kevin-stuart** [comment]
OK, I see, thanks for the quick reply! Any plans to support SOCKS5 username/password in the future?

**Comment by hmgle** [comment]
Yes, I will implement it later.

**Comment by kevin-stuart** [comment]
Very cool. Keep up the good work!

**Comment by hmgle** [comment]
@kevin-stuart The SOCKS5' auth has been supported. You can set the `socks5_username` and `socks5_password` variables in the configuration file.
Thank you for the feedback.
