### ISSUE TITLE
对 MacOS 的支持

### ISSUE THREAD

**Issue by yangchuansheng** [hmgle/graftcp#2]
你好，请问目前是否支持 MacOS 系统？

**Comment by hmgle** [comment]
- [Does it support macOS?](https://github.com/hmgle/graftcp/#does-it-support-macos)
- [支持 macOS 吗？](https://github.com/hmgle/graftcp/blob/master/README.zh-CN.md#%E6%94%AF%E6%8C%81-macos-%E5%90%97)

欢迎感兴趣的同学添加对 MacOS 的支持。

**Comment by sh1luo** [comment]
支持Windows吗？

**Comment by hmgle** [comment]
> 支持Windows吗？

仅支持 Linux。Windows 的 WSL 2 应该也可以，我没有试过。

**Comment by hmgle** [comment]
决定不支持其他平台了。
