### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [hmgle/graftcp#3]
I would like to point out that identifiers like “[`_GRAFTCP_H`](https://github.com/hmgle/graftcp/blob/00a5c0a91b4fa89d7ce6867efc6f93ee1904a4a9/graftcp.h#L15 "Update candidate")” and “[`_STRING_SET_H`](https://github.com/hmgle/graftcp/blob/00a5c0a91b4fa89d7ce6867efc6f93ee1904a4a9/string-set.h#L15 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by hmgle** [comment]
@elfring Thank you for your comments, but can you elaborate on what you mean by the "expected naming convention of the C language standard"? These macros are never used anywhere other than for replacing 'pragma once', but I will adjust the identifiers for shorter.
