### ISSUE TITLE
sudo make install 后 rm -rf graftcp文件夹后 ,graftcp-local service fail

### ISSUE THREAD

**Issue by xtccc** [hmgle/graftcp#31]
**Describe the bug**
正常安装 
make install
rm -rf graftcp
sudo systemctl restart graftcp-local.service
sudo systemctl status graftcp-local.service # 这时服务就坏了
(base) xtcc@archwork:~ $ sudo systemctl status graftcp-local.service                                             127 ↵
● graftcp-local.service - Translate graftcp TCP to SOCKS5 or HTTP proxy
     Loaded: loaded (/etc/systemd/system/graftcp-local.service; enabled; vendor preset: disabled)
     Active: inactive (dead) since Fri 2020-10-30 18:54:40 CST; 4min 14s ago
  Condition: start condition failed at Fri 2020-10-30 18:54:40 CST; 4min 14s ago
             └─ ConditionFileIsExecutable=/home/xtcc/graftcp/graftcp-local/graftcp-local was not met
    Process: 33724 ExecStart=/bin/bash -c /home/xtcc/graftcp/graftcp-local/graftcp-local (code=exited, status=0/SUCCES>
   Main PID: 33724 (code=exited, status=0/SUCCESS)

10月 30 18:53:36 archwork systemd[1]: Started Translate graftcp TCP to SOCKS5 or HTTP proxy.
10月 30 18:53:36 archwork bash[33724]: [2020-10-30 18:53:36] [NOTICE] graftcp-local start
10月 30 18:53:36 archwork bash[33724]: [2020-10-30 18:53:36] [INFO] select_proxy_mode: auto
10月 30 18:53:36 archwork bash[33724]: [2020-10-30 18:53:36] [INFO] graftcp-local start listening :2233...
10月 30 18:54:40 archwork systemd[1]: Stopping Translate graftcp TCP to SOCKS5 or HTTP proxy...
10月 30 18:54:40 archwork bash[33724]: [2020-10-30 18:54:40] [NOTICE] graftcp-local stop
10月 30 18:54:40 archwork systemd[1]: graftcp-local.service: Succeeded.
10月 30 18:54:40 archwork systemd[1]: Stopped Translate graftcp TCP to SOCKS5 or HTTP proxy.
10月 30 18:54:40 archwork systemd[1]: Condition check resulted in Translate graftcp TCP to SOCKS5 or HTTP proxy being >

**Desktop (please complete the following information):**
 - OS: archlinux
 - Browser vivaldi
 - Version :Linux archwork 5.9.1-arch1-1

**Additional context**
应该是安装没安装完全吧.希望修复一下.或者把包弄成"."开头的,隐藏下,不然很难受啊

**Comment by hmgle** [comment]
目前安装的启动脚本配置的启动二进制路径为原目录，因此把原目录删除后会启动不了，有空我再对安装这一块改进一下。

**Comment by hmgle** [comment]
最新版已更新了安装方式，make install 默认会把 graftcp-local 安装到 `/usr/local/bin` 路径。
如果是 Arch Linux 建议从 [AUR](https://aur.archlinux.org/packages/graftcp/) 安装，Debian 系可以下载 [deb 包](https://github.com/hmgle/graftcp/releases/download/v0.3.1/graftcp_0.3.1-1_amd64.deb) 安装。
