### ISSUE TITLE
Why not merge local and graftcp? 

### ISSUE THREAD

**Issue by chaoqing** [hmgle/graftcp#33]
May I ask whether there is any concern on merging the graftcp-local and graftcp into one single binary?

It seems strange to me if I just want to proxy one command but need to open another terminal for local to running.

If it is already designed behavior which make merging in framework level a hard task, we can do it the simple way by spawn another thread inside go for local. Is this a valid solution?

**Comment by hmgle** [comment]
Good question.
I will explain the reason later. In short, the goal of merging into one is almost impossible to achieve.

**Comment by chaoqing** [comment]
Thanks for the explanation and I expected the problem in merging in framework level. That's why I proposed another much more hacker way. We can first use the same method as busybox to merge two binary into one (which I have done in other project) and then open one goroutine for local server, another one for os/exec the graftcp command. We just need be sure to handle the input/output stream correctly.

**Comment by hmgle** [comment]
Interesting. RP welcome!

**Comment by hmgle** [comment]
[v0.4.0](https://github.com/hmgle/graftcp/releases/tag/v0.4.0) has been released, a new command `mgraftcp` has been added to support this feature.
