### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [hmgle/graftcp#4]
Would you like to add more error handling for return values from functions like the following?
- [calloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/calloc.html "Memory allocation") ⇒ [str_set_new](https://github.com/hmgle/graftcp/blob/81b3870c0f839df088d0050e326edfc4f914f7ee/string-set.c#L33)
- [ptrace](http://man7.org/linux/man-pages/man2/ptrace.2.html "Process trace") ⇒ [clone_pre_handle](https://github.com/hmgle/graftcp/blob/fcd65772596b0652d04874bd12de2ff3db4838f8/main.c#L141)

**Comment by elfring** [comment]
Thanks for [your small source code adjustment](https://github.com/hmgle/graftcp/commit/68eb559b97b9c28ace5614b27e80a13886b19650 "Handle calloc error").

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

**Comment by hmgle** [comment]
@elfring Source Code Analysis Tools look very useful, but I don't rely on them now.

**Comment by elfring** [comment]
* Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "Software development with AspectC++?")?
* How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by hmgle** [comment]
@elfring https://github.com/droe/sslsplit/issues/38
I agree with @droe about this matter.
