### ISSUE TITLE
批量添加黑白名单

### ISSUE THREAD

**Issue by lhllhx** [hmgle/graftcp#46]
我看到样例是只能一个个添加ip
是否可以考虑增加批量添加的功能
例如：192.168.0.0-192.168.0.255

另外讨论另一个小功能 是否在里面是否可以实现url黑白名单

**Comment by hmgle** [comment]
IP 这个可以实现，不过这个功能不太紧急，后面有空可以加下。
如果是 URL 的话无法实现，目前 graftcp 工作在 L4 层，获取不到流量的域名信息。

**Comment by lhllhx** [comment]
> IP 这个可以实现，不过这个功能不太紧急，后面有空可以加下。 如果是 URL 的话无法实现，目前 graftcp 工作在 L4 层，获取不到流量的域名信息。

url可以考虑这么实现，每隔一段时间，程序自身解析url，再把解析到的ip加入到白名单里面。
