### ISSUE TITLE
wget 可以正常使用，但 curl 不行

### ISSUE THREAD

**Issue by everplus** [hmgle/graftcp#48]
centos 7 x64，使用 graftcp 运行
wget 都可以正常使用，curl ip 地址可以，curl 带域名不行，会卡住
会无线循环进入 trace_syscall_entering 约 1 秒 1 次，pinfp->csn 值为 7，SYS_poll

可能是什么原因？

**Comment by hmgle** [comment]
执行 graftcp 时可以用 `sudo journalctl -f -u graftcp-local.service` 观察下日志，看看是否有目标地址的IP输出。
有可能是 DNS 解析出问题了。

**Comment by everplus** [comment]
graftcp-local 我看过没有任何日志

**Comment by everplus** [comment]
我用nodejs写了一个简单的脚本，只是用了dns.resolve，就会卡住，不进回调

**Comment by hmgle** [comment]
用 graftcp 启动 curl 时可以加下 `-v` 或 `--trace -` 选项看下执行到哪一步失败了。从上面的 graftcp-local 没有日志输出来看，应该发生在建立 TCP 连接之前。

**Comment by everplus** [comment]
--verbose 和 --trace - 都没有任何输出
我用 strace 记录了日志，见附件

[strace.txt](https://github.com/hmgle/graftcp/files/8362469/strace.txt)

**Comment by hmgle** [comment]
> --verbose 和 --trace - 都没有任何输出 我用 strace 记录了日志，见附件
> 
> [strace.txt](https://github.com/hmgle/graftcp/files/8362469/strace.txt)

想确定一下上面的确切执行命令，是 `graftcp curl -v https://github.com` 和 `graftcp curl --trace - https://github.com` 都没有任何输出吗？

**Comment by everplus** [comment]
![image](https://user-images.githubusercontent.com/2535751/160445667-5a7e7d12-f486-4ce9-8434-f61ab45f463a.png)
![image](https://user-images.githubusercontent.com/2535751/160445785-5fd619c4-a7c6-4bdf-93f7-5f2f50c4747a.png)

**Comment by hmgle** [comment]
@everplus  请问下 curl 的版本是多少，我看下我这边能不能复现。

**Comment by everplus** [comment]
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.19.1 Basic ECC zlib/1.2.7 libidn/1.28 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz

我感觉不是 curl 版本的问题，相同的版本在其他机器上是好的，我出故障的是一台 kvm 虚拟机，猜测和虚拟化有一些关系
