### ISSUE TITLE
Awesome project

### ISSUE THREAD

**Issue by scatterfafafa** [hmgle/graftcp#49]
Please add more proxy model.. like ss, ssr..

**Comment by hmgle** [comment]
As most proxy tools (including ss, ssr) already support SOCKS5 and HTTP proxy protocol, I don't think it is necessary to adapt a separate protocol for each proxy tool. Just supporting SOCKS5 and HTTP is enough.

If you still need more proxy model, [gg](https://github.com/mzz2017/gg) may be help.
