### ISSUE TITLE
建议增加dotfiles配置

### ISSUE THREAD

**Issue by Nriver** [hmgle/graftcp#53]
建议增加从 `~/graftcp-local/graftcp-local.conf` 读取配置的选择，方便非root用户通过dotfiles管理配置

**Comment by hmgle** [comment]
graftcp-local 是支持 `-config` 指定配置路径的。
你的意思是否指默认加载 `~/graftcp-local/graftcp-local.conf` 配置呢？

**Comment by Nriver** [comment]
是的，默认从dotfiles里读取配置。

**Comment by hmgle** [comment]
已增加 `~/.graftcp-local/graftcp-local.conf` 配置文件加载，加载顺序请见： https://github.com/hmgle/graftcp#configuration

如有问题麻烦重新打开 issue。

**Comment by hmgle** [comment]
准备把 ~/.graftcp-local/graftcp-local.conf 路径更新为符合 [XDG 基本路径规范](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) 的路径：尝试读取 `$XDG_CONFIG_HOME/graftcp/graftcp-local.conf` 作为用户配置。
> $XDG_CONFIG_HOME defines the base directory relative to which user-specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

**Comment by Nriver** [comment]
是`$XDG_CONFIG_HOME/.graftcp/graftcp-local.conf`吗? 少了一个点

**Comment by hmgle** [comment]
> 是`$XDG_CONFIG_HOME/.graftcp/graftcp-local.conf`吗? 少了一个点

不是，因为 $XDG_CONFIG_HOME 一般已经有点了。可以用 `ls -a ~/.config` 看到里面大部分都是不带点的。

**Comment by Nriver** [comment]
哦，我试了一下Debian和manjaro都没有 $XDG_CONFIG_HOME，echo出来是空的，我cd过去就回到用户根目录了。

原来是指 .config 目录啊，那确实是不用再加点了。
