### ISSUE TITLE
_amd asset not found in v0.5.0

### ISSUE THREAD

**Issue by SkyperTHC** [hmgle/graftcp#57]
current release v0.5.0 only shows source archives and no longer the pre-compiled binary release. 

Can you add the binary releases please?

**Comment by hmgle** [comment]
Thank you for the suggestion. However, packaging process for multiple Linux platforms and multi-architectures will require a significant amount of effort and time, which I currently do not have. Moreover, i am not familiar with the packaging process for some Linux platform, which could result in suboptimal or even incorrect binaries.

Therefore, I would recommend building from source for your specific Linux distribution and architecture. Please let me know if you have any further questions or suggestions.
