### ISSUE TITLE
Improve efficiency / speed

### ISSUE THREAD

**Issue by m3dus444** [hmgle/graftcp#58]
Hi man ! The work you made is insane, it works perfeclty for me. I ended up here because i needed to proxy my traffic from some Go pentesting tools (like Kerbrute).
I wanted to say congrats, and also bring to light something you could improve : speed. 
I don't know if it's possible for you to add an option to set a number of threads or something like that, but i've noticed that it took me like 25 min to make a basic kerbrute attack (which usually takes less than 1 min). 

I was wondering if theres a way for you to improve that, because it can be very unpractical if we need to proxy a lot of requests. 

Anyway, that is said, you did a great job man. Thanks a lot ! ❤️‍🔥

**Comment by hmgle** [comment]
Thank you for your feedback!
I'm glad to hear that the tool works well for you. May I confirm the version you are using? The latest version(v0.6.1) has greatly improved its speed through seccomp-bpf. According to my tests, it is now very close to the speed of the original program. If you are already using the latest version(v0.6.1), please let me know and it would be great if you could provide a speed comparison with the original program.
