### ISSUE TITLE
继续打包二进制文件啊！

### ISSUE THREAD

**Issue by ugvfpdcuwfnh** [hmgle/graftcp#59]
新版本的release只有源代码，没有打包好的二进制文件。

可是源码打包的依赖又被墙了....

我就是因为被墙了才要安装graftcp，然后打包又需要翻墙，这是在讽刺么？  =_=！

**Comment by hmgle** [comment]
暂时不打算用手动方式打包了，原因在 #57 提到过。后面有空可以研究下发布时用 github actions 打包各个发行版的二进制包。
