### ISSUE TITLE
graftcp go get -v这一步必须的么?

### ISSUE THREAD

**Issue by wxlg1117** [hmgle/graftcp#6]
1:
git clone https://github.com/hmgle/graftcp.git
cd graftcp
make
后 graftcp位于当前源码目录,而graftcp-local出现在go/bin下;

2:
通过 graftcp 安装来自 golang.org 的 Go 包:
./graftcp go get -v golang.org/x/net/proxy

卡在这里了,如果跳过这步直接启用graftcp 好像某些能用有些不能用?
graftcp wget 之类的能用,因为请求会出现在graftcp-local实时刷新的日志里
graftcp yum 之类的好像不能?graftcp-local实时刷新的日志里完全没有请求

**Comment by hmgle** [comment]
@wxlg1117 
1. make 之后编译生成的 `graftcp`  位于当前目录，而 `graftcp-local` 是通过 `	go get -v github.com/hmgle/graftcp/graftcp-local` 获取的，所以位于 go/bin 目录。README 里面的 demo 演示图没有更新，之前 `graftcp-local` 也是在当前目录生成的。
2. `./graftcp go get -v golang.org/x/net/proxy` 卡住应该是你主机进行 golang.org 域名解析时受到 DNS 污染了，可以贴下 `graftcp-local` 打印出来的 IP。如果确定是 DNS 污染，需要先用 `dnscrypt-proxy` 或 `ChinaDNS` + `ss` 等方案解决 DNS 污染问题。

yum 命令方便贴下打印吗？

**Comment by roachsinai** [comment]
感谢这个工具，不过希望可以更新一下`README.md`，说明`graftcp go get -v golang.org/x/net/proxy`只是演示。

**Comment by hmgle** [comment]
> 感谢这个工具，不过希望可以更新一下`README.md`，说明`graftcp go get -v golang.org/x/net/proxy`只是演示。

不错的建议，已将副标题修改为 Demo，这样更贴切点。

**Comment by 578141611** [comment]
针对于需要google翻墙处理的下载go-lang包，可以使用离线下载的方式，把包下好了，然后解压放到$gopath/golang.org/x/net目录
