### ISSUE TITLE
可以添加处理UDP数据的功能吗？

### ISSUE THREAD

**Issue by sunlewuyou** [hmgle/graftcp#61]
不想配置ChinaDNS，想要尽可能简单，开箱即用，请问后续会考虑添加处理UDP数据的功能吗？

**Comment by hmgle** [comment]
使用 ptrace 的方式比较难实现 UDP 数据的处理，目前也没有计划添加这个功能。但用 Linux 的 network_namespaces 可以比较方便的实现，目前也有相关的工具，你可以试试：

- [nsproxy](https://github.com/nlzy/nsproxy)
- [passt](https://github.com/hmgle/passt)

上面的 passt 是我添加了 proxy 后的版本。
