### ISSUE TITLE
How to let an application that started or enabled by  "systemctl " use graftcp on Linux?

### ISSUE THREAD

**Issue by zwl1619** [hmgle/graftcp#71]
How to let an application that started or enabled by  "systemctl " use graftcp?
For example, I installed sing-box, manage it with  the commands below:
```
sudo systemctl enable sing-box
sudo systemctl disable sing-box
sudo systemctl start sing-box
sudo systemctl stop sing-box
sudo systemctl kill sing-box
sudo systemctl restart sing-box
```
How to launch sing-box via graftcp?

**Comment by hmgle** [comment]
Modify your Systemd Unit Configuration file's ExecStart line:
From: `ExecStart=/path/to/app`
To: `ExecStart=graftcp /path/to/app`
